# This is a basic workflow to help you get started with Actions

name: Verify Original Branch

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  get-source-branch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - id: step1
        run: echo "::set-output name=test::$(if [ "$(git log | grep e60ea364d17ff0d92ea8189cf1ee8b4bd40505c0)" != '' ] ; then echo 1; else echo 0 ; fi)"
        shell: bash
  check-source-branch:
    runs-on: ubuntu-latest
    needs: get-source-branch
    if: ${{ needs.get-source-branch.outputs.test == 0 }}
    steps:
      - uses: superbrothers/close-pull-request@v2.0.0
        with:
          comment: "This branch seems to be based on a branch other than Live. Please see the `git rebase` [wiki entry](https://github.com/vcreativeinc/legacy-ppo/wiki/Git-Good#you-accidentally-created-your-branch-from-a-branch-that-was-not-live-or-main-or-whatever-branch-you-were-supposed-to-use)."
